//! CI guard against drift between `desktop-ui/src/bindings.ts` and the
//! tauri-specta builder.
//!
//! If this fails locally:
//!   $ cargo tauri dev   (any debug run regenerates the bindings)
//!   $ git add desktop-ui/src/bindings.ts
//!
//! If this fails in CI: the developer forgot to commit a regenerated
//! bindings file. Pull the diff from CI logs.

use specta_typescript::Typescript;

#[test]
fn bindings_are_current() {
    let builder = desktop::specta_builder::build_specta();
    let header = "// @ts-nocheck\n// Auto-generated by tauri-specta — DO NOT EDIT.\n";

    let generated = builder
        .export_str(
            Typescript::default()
                .header(header)
                .bigint(specta_typescript::BigIntExportBehavior::Number),
        )
        .expect("specta export_str failed");

    let bindings_path =
        std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../desktop-ui/src/bindings.ts");

    let on_disk = std::fs::read_to_string(&bindings_path).unwrap_or_else(|_| String::new());

    if on_disk != generated {
        // Write the new file so the developer can `git diff` it.
        let _ = std::fs::write(&bindings_path, &generated);
        panic!(
            "desktop-ui/src/bindings.ts is out of date.\n\
             Re-generated and written to disk — run `git diff desktop-ui/src/bindings.ts` to inspect.\n\
             Then commit the change."
        );
    }
}
