[package]
name = "feature-todo"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
tools-core.workspace = true
storage.workspace = true
async-trait.workspace = true
serde = { workspace = true }
serde_json.workspace = true
tokio.workspace = true
tracing.workspace = true
chrono = { workspace = true }
uuid = { workspace = true }
rrule.workspace = true
pgvector = { workspace = true }
sqlx.workspace = true

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "test-util"] }
