[package]
name = "storage"
version.workspace = true
edition.workspace = true

[dependencies]
ai-core.workspace = true
bus = { path = "../bus" }
common.workspace = true
tools-core.workspace = true
klynt-git-utils = { path = "../klynt-git-utils" }
sqlx.workspace = true
lance.workspace = true
lance-io.workspace = true
lancedb.workspace = true
arrow-array.workspace = true
arrow-schema.workspace = true
uuid.workspace = true
jiff.workspace = true
dashmap.workspace = true
serde.workspace = true
serde_json.workspace = true
specta = { workspace = true }
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tracing.workspace = true
futures-util.workspace = true

[dev-dependencies]
tokio.workspace = true
tempfile = { workspace = true }
