pub mod aggregator;
pub mod batch_writer;
pub mod bucket_aggregator;
pub mod config;
pub mod dashboard_emitter;
pub mod distraction;
pub mod distraction_analyzer;
pub mod engine;
pub mod events;
pub mod feature;
pub mod focus;
pub mod handler;
pub mod insights;
pub mod intelligence;
pub mod nudge;
pub mod patterns;
pub mod project_detector;
pub mod repos;
pub mod tool;
pub mod tracker;
pub mod types;

pub use aggregator::DailyAggregator;
pub use config::ProductivityConfig;
pub use engine::ProductivityEngine;
pub use feature::{productivity_migrations, ProductivityFeature};
pub use focus::FocusManager;
pub use handler::ProductivityHandler;
pub use nudge::NudgeService;
pub use patterns::{ProductivityPatternAnalyzer, ProductivityPatterns};
pub use tool::ProductivityTool;
pub use types::*;
