[package]
name = "klyntbot-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
klyntbot-core.workspace = true
klyntbot-config.workspace = true
klyntbot-bus.workspace = true
klyntbot-providers.workspace = true
klyntbot-agent.workspace = true
klyntbot-channels.workspace = true
klyntbot-cron.workspace = true
klyntbot-heartbeat.workspace = true
klyntbot-session.workspace = true
klyntbot-tools.workspace = true
clap = { workspace = true }
rustyline.workspace = true
tokio = { workspace = true }
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
dirs.workspace = true
