[package]
name = "cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
common.workspace = true
config.workspace = true
bus.workspace = true
providers.workspace = true
agent.workspace = true
channels.workspace = true
scheduling.workspace = true
storage.workspace = true
heartbeat.workspace = true
session.workspace = true
tools.workspace = true
goal.workspace = true
plan.workspace = true
dashboard.workspace = true
plugin-runtime.workspace = true
clap = { workspace = true }
rustyline.workspace = true
tokio = { workspace = true }
tokio-util.workspace = true
anyhow.workspace = true
tracing.workspace = true
tracing-subscriber = { workspace = true }
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
dirs.workspace = true
reqwest.workspace = true
url.workspace = true
tokio-tungstenite = { workspace = true }
async-imap = { workspace = true }
native-tls = { workspace = true }
tokio-native-tls = { workspace = true }
lettre = { workspace = true }
crossterm = { workspace = true }
chrono-tz = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile.workspace = true
