import type { RecommendedMcpServer } from "../../../lib/types";

export const recommendedServers: RecommendedMcpServer[] = [
  {
    name: "github",
    author: "GitHub",
    description: "Repository management, issues, pull requests, and code search",
    icon: "github",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-github"],
    envKeys: ["GITHUB_PERSONAL_ACCESS_TOKEN"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    oauthProvider: "github",
  },
  {
    name: "linear",
    author: "Linear",
    description: "Issue tracking, project management, and team workflows",
    icon: "linear",
    transport: "stdio",
    command: "npx",
    args: ["-y", "linear-mcp-server"],
    envKeys: ["LINEAR_API_KEY"],
    docsUrl: "https://github.com/modelcontextprotocol/linear-server",
    oauthProvider: "linear",
  },
  {
    name: "notion",
    author: "Notion",
    description: "Page and database management for Notion workspaces",
    icon: "notion",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@notionhq/notion-mcp-server"],
    envKeys: ["OPENAPI_MCP_HEADERS"],
    docsUrl: "https://github.com/makenotion/notion-mcp-server",
    oauthProvider: "notion",
  },
  {
    name: "slack",
    author: "Slack",
    description: "Channel messaging, user lookup, and workspace management",
    icon: "slack",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-slack"],
    envKeys: ["SLACK_BOT_TOKEN"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
    oauthProvider: "slack",
  },
  {
    name: "google-drive",
    author: "Google",
    description: "File search and content access for Google Drive",
    icon: "google-drive",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@modelcontextprotocol/server-gdrive"],
    envKeys: ["GDRIVE_CLIENT_ID", "GDRIVE_CLIENT_SECRET"],
    docsUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive",
    oauthProvider: "google-drive",
  },
  {
    name: "google-calendar",
    author: "Google",
    description: "Calendar events, scheduling, and availability management",
    icon: "google-calendar",
    transport: "stdio",
    command: "npx",
    args: ["-y", "@cocal/google-calendar-mcp"],
    envKeys: ["GOOGLE_CALENDAR_CLIENT_ID", "GOOGLE_CALENDAR_CLIENT_SECRET"],
    docsUrl: "https://github.com/nate-cocal/google-calendar-mcp",
    oauthProvider: "google-calendar",
  },
];
