export { Dashboard } from "./components/Dashboard";
export { ProductivityStrip } from "./components/ProductivityStrip";
export { SummaryPanel } from "./components/SummaryPanel";
export { ActivityFeed } from "./components/productivity/ActivityFeed";
export { AddGoalDialog } from "./components/productivity/AddGoalDialog";
export { AutoFocusToast } from "./components/productivity/AutoFocusToast";
export { FocusStateIndicator } from "./components/productivity/FocusStateIndicator";
export { FocusTrayIndicator } from "./components/productivity/FocusTrayIndicator";
export { GoalsProgress } from "./components/productivity/GoalsProgress";
export { HourlyHeatmap } from "./components/productivity/HourlyHeatmap";
export { PatternsCard } from "./components/productivity/PatternsCard";
export { ProductivityScoreRing, ScoreBar } from "./components/productivity/ProductivityScoreRing";
export { ActivityTrack } from "./components/views/ActivityTrack";
export type { SessionBlock } from "./components/views/ActivityTrack";
export { mergeActivitySessions } from "./lib/activity-sessions";
export type { MergeableEvent, MergedSession } from "./lib/activity-sessions";
export { AppIcon, getAppColor, scoreColor, qualityToColor } from "./lib/productivity";
