//! Single source of truth for the tauri-specta Builder.
//!
//! Both `main.rs` (production runtime) and `tests/bindings_are_current.rs`
//! (CI drift check) call `build_specta()` to ensure they see the *same*
//! command + event list. Add new commands and events here.

use tauri_specta::{collect_commands, collect_events, Builder};

pub fn build_specta() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            // agents
            crate::commands::agents::agent_list_profiles,
            crate::commands::agents::agent_read_file,
            crate::commands::agents::agent_write_file,
            crate::commands::agents::agent_create_profile,
            crate::commands::agents::agent_create_skill,
            crate::commands::agents::agent_delete_file,
            // annotations
            crate::commands::annotations::annotation_create,
            crate::commands::annotations::annotation_update,
            crate::commands::annotations::annotation_delete,
            crate::commands::annotations::annotation_list_for_note,
            crate::commands::annotations::annotation_get_ai_suggestion,
            crate::commands::annotations::note_get_linked_context,
            // areas
            crate::commands::areas::area_list,
            crate::commands::areas::area_create,
            crate::commands::areas::area_update,
            crate::commands::areas::area_delete,
            crate::commands::areas::area_reorder,
            // autotuner
            crate::commands::autotuner::autotuner_status,
            crate::commands::autotuner::autotuner_history,
            crate::commands::autotuner::autotuner_revert,
            crate::commands::autotuner::autotuner_pause,
            crate::commands::autotuner::autotuner_resume,
            crate::commands::autotuner::autotuner_set_pace,
            crate::commands::autotuner::autotuner_get_toast_count,
            crate::commands::autotuner::autotuner_increment_toast_count,
            // capture
            crate::commands::capture::capture_status,
            crate::commands::capture::capture_shell_hook_status,
            crate::commands::capture::capture_install_shell_hook,
            crate::commands::capture::capture_uninstall_shell_hook,
            crate::commands::capture::capture_get_ingestion_token,
            crate::commands::capture::capture_regenerate_ingestion_token,
            // chat
            crate::commands::chat::chat_threads,
            crate::commands::chat::chat_messages,
            crate::commands::chat::chat_send,
            crate::commands::chat::chat_pin_thread,
            crate::commands::chat::chat_rename_thread,
            crate::commands::chat::chat_delete_thread,
            crate::commands::chat::chat_respond_interaction,
            crate::commands::chat::chat_get_session,
            crate::commands::chat::chat_list_sessions_by_project,
            crate::commands::chat::chat_delete_stale_sessions,
            crate::commands::chat::chat_cancel,
            // coding_memory
            crate::commands::coding_memory::coding_memory_status,
            crate::commands::coding_memory::coding_memory_cli_health,
            crate::commands::coding_memory::coding_memory_session_replay,
            crate::commands::coding_memory::coding_memory_enable_cli,
            crate::commands::coding_memory::coding_memory_disable_cli,
            crate::commands::coding_memory::coding_memory_diagnose_cli,
            crate::commands::coding_memory::coding_memory_browser,
            crate::commands::coding_memory::coding_memory_activity,
            crate::commands::coding_memory::coding_memory_cost,
            crate::commands::coding_memory::coding_memory_sensitivity,
            crate::commands::coding_memory::coding_memory_distill_now,
            crate::commands::coding_memory::coding_memory_recall_index,
            crate::commands::coding_memory::coding_memory_recall_timeline,
            crate::commands::coding_memory::coding_memory_recall_fetch,
            crate::commands::coding_memory::coding_memory_check_dead_ends,
            crate::commands::coding_memory::coding_memory_recall_facts_as_of,
            crate::commands::coding_memory::coding_memory_recall_change_history,
            crate::commands::coding_memory::coding_memory_recall_decision_points,
            crate::commands::coding_memory::coding_memory_recall_log,
            crate::commands::coding_memory::coding_memory_session_replay_recall_overlay,
            crate::commands::coding_memory::coding_memory_mirror_alerts_feed,
            crate::commands::coding_memory::coding_memory_mirror_alert_action,
            crate::commands::coding_memory::coding_memory_effectiveness_trends,
            crate::commands::coding_memory::coding_memory_reforge_cycle_list,
            crate::commands::coding_memory::coding_memory_reforge_cycle_diff,
            crate::commands::coding_memory::coding_memory_project_skills_for_repo,
            // cognitive
            crate::commands::cognitive::cognitive_user_model,
            crate::commands::cognitive::cognitive_facts_list,
            crate::commands::cognitive::cognitive_episodic_list,
            crate::commands::cognitive::cognitive_rules_list,
            crate::commands::cognitive::cognitive_memory_stats,
            crate::commands::cognitive::memory_health,
            crate::commands::cognitive::coaching_situation,
            crate::commands::cognitive::coaching_signals,
            crate::commands::cognitive::coaching_patterns,
            crate::commands::cognitive::coaching_feedback_stats,
            crate::commands::cognitive::coaching_router_status,
            crate::commands::cognitive::coaching_pending_interventions,
            crate::commands::cognitive::memory_reference_detail,
            crate::commands::cognitive::cognitive_system_status,
            crate::commands::cognitive::cognitive_fact_create,
            crate::commands::cognitive::cognitive_fact_update,
            crate::commands::cognitive::cognitive_fact_delete,
            crate::commands::cognitive::cognitive_rule_create,
            crate::commands::cognitive::cognitive_rule_deactivate,
            crate::commands::cognitive::cognitive_run_compaction,
            crate::commands::cognitive::coaching_reset_dismissals,
            crate::commands::cognitive::coaching_clear_signals,
            crate::commands::cognitive::coaching_submit_feedback,
            crate::commands::cognitive::coaching_report_ignored,
            crate::commands::cognitive::coaching_intervention_log,
            crate::commands::cognitive::coaching_seed_patterns,
            crate::commands::cognitive::cognitive_inject_event,
            crate::commands::cognitive::cognitive_event_log,
            crate::commands::cognitive::cognitive_pipeline_log,
            crate::commands::cognitive::cognitive_graph_data,
            crate::commands::cognitive::cognitive_graph_expand_topic,
            // columns
            crate::commands::columns::custom_column_list,
            crate::commands::columns::custom_column_create,
            crate::commands::columns::custom_column_update,
            crate::commands::columns::custom_column_delete,
            crate::commands::columns::custom_column_reorder,
            crate::commands::columns::custom_column_values,
            crate::commands::columns::custom_column_value_set,
            crate::commands::columns::custom_column_value_delete,
            // cron
            crate::commands::cron::cron_list,
            crate::commands::cron::cron_status,
            crate::commands::cron::cron_enable,
            crate::commands::cron::cron_run,
            crate::commands::cron::cron_delete,
            crate::commands::cron::cron_create,
            crate::commands::cron::cron_update,
            // distraction
            crate::commands::distraction::distraction_dismiss,
            crate::commands::distraction::distraction_allow_temp,
            crate::commands::distraction::distraction_allow_session,
            crate::commands::distraction::distraction_learned_rules,
            crate::commands::distraction::distraction_delete_rule,
            // entities
            crate::commands::entities::entity_search,
            crate::commands::entities::entity_merge,
            crate::commands::entities::entity_get_neighborhood,
            // entity_links
            crate::commands::entity_links::entity_link_create,
            crate::commands::entity_links::entity_link_delete,
            crate::commands::entity_links::entity_links_for_entity,
            // fabric
            crate::commands::fabric::fabric_graph_base,
            crate::commands::fabric::fabric_graph_expand,
            crate::commands::fabric::fabric_graph_action,
            // finance
            crate::commands::finance::finance_accounts,
            crate::commands::finance::finance_transactions,
            crate::commands::finance::finance_transactions_filtered,
            crate::commands::finance::finance_budget_usage,
            crate::commands::finance::finance_portfolios,
            crate::commands::finance::finance_investments,
            crate::commands::finance::finance_investments_filtered,
            crate::commands::finance::finance_goals,
            crate::commands::finance::finance_liabilities,
            crate::commands::finance::finance_net_worth,
            crate::commands::finance::finance_exchange_rates,
            crate::commands::finance::finance_account_create,
            crate::commands::finance::finance_account_update,
            crate::commands::finance::finance_account_delete,
            crate::commands::finance::finance_transaction_create,
            crate::commands::finance::finance_transaction_delete,
            crate::commands::finance::finance_budget_create,
            crate::commands::finance::finance_budget_update,
            crate::commands::finance::finance_budget_delete,
            crate::commands::finance::finance_goal_create,
            crate::commands::finance::finance_goal_update,
            crate::commands::finance::finance_goal_delete,
            crate::commands::finance::finance_liability_create,
            crate::commands::finance::finance_liability_update,
            crate::commands::finance::finance_liability_delete,
            crate::commands::finance::finance_portfolio_create,
            crate::commands::finance::finance_investment_create,
            crate::commands::finance::finance_investment_update,
            crate::commands::finance::finance_allocation_target_upsert,
            crate::commands::finance::finance_allocation_targets,
            crate::commands::finance::finance_investment_tx_create,
            crate::commands::finance::finance_investment_txs,
            crate::commands::finance::finance_report_spending,
            crate::commands::finance::finance_report_income,
            crate::commands::finance::finance_report_trends,
            crate::commands::finance::finance_monthly_summary,
            crate::commands::finance::finance_daily_spending,
            crate::commands::finance::finance_period_summary,
            // focus
            crate::commands::focus::focus_install_shortcuts,
            crate::commands::focus::focus_shortcuts_installed,
            crate::commands::focus::focus_activate,
            crate::commands::focus::focus_deactivate,
            crate::commands::focus::focus_extend,
            crate::commands::focus::focus_active,
            // groups
            crate::commands::groups::group_list,
            crate::commands::groups::group_create,
            crate::commands::groups::group_update,
            crate::commands::groups::group_delete,
            crate::commands::groups::group_reorder,
            // journey
            crate::commands::journey::journey_milestones,
            crate::commands::journey::journey_mark_complete,
            crate::commands::journey::journey_item_count,
            // key_results
            crate::commands::key_results::key_result_create,
            crate::commands::key_results::key_result_update,
            crate::commands::key_results::key_result_update_metric,
            crate::commands::key_results::key_result_delete,
            // knowledge_health
            crate::commands::knowledge_health::knowledge_health_summary,
            crate::commands::knowledge_health::knowledge_topic_detail,
            // language
            crate::commands::language::language_translate_breakdown,
            crate::commands::language::language_evaluate_translation,
            crate::commands::language::language_save_vocabulary,
            crate::commands::language::language_detect_confusables,
            crate::commands::language::language_enrich_annotation,
            crate::commands::language::language_quick_translate,
            // launcher
            crate::commands::launcher::launcher_search,
            crate::commands::launcher::launcher_execute,
            crate::commands::launcher::launcher_dashboard,
            crate::commands::launcher::launcher_clipboard_paste,
            crate::commands::launcher::launcher_clipboard_delete,
            crate::commands::launcher::launcher_clipboard_pin,
            crate::commands::launcher::launcher_run_script,
            crate::commands::launcher::launcher_system_command,
            crate::commands::launcher::launcher_window_action,
            crate::commands::launcher::launcher_open_app,
            // mirror
            crate::commands::mirror::get_mirror_state,
            crate::commands::mirror::get_routing_history,
            crate::commands::mirror::get_mirror_narratives,
            crate::commands::mirror::get_pending_snippets,
            crate::commands::mirror::submit_mirror_feedback,
            crate::commands::mirror::generate_mirror_response,
            crate::commands::mirror::approve_meta_rule,
            crate::commands::mirror::dismiss_meta_rule,
            crate::commands::mirror::get_brain_versions,
            crate::commands::mirror::revert_brain_version,
            crate::commands::mirror::kill_trial,
            crate::commands::mirror::continue_trial,
            // morning_briefing
            crate::commands::morning_briefing::morning_briefing_summary,
            // notes
            crate::commands::notes::note_list,
            crate::commands::notes::note_get,
            crate::commands::notes::note_create,
            crate::commands::notes::note_update,
            crate::commands::notes::note_delete,
            crate::commands::notes::note_search,
            crate::commands::notes::note_search_semantic,
            crate::commands::notes::note_search_hybrid,
            crate::commands::notes::note_links_all,
            crate::commands::notes::note_list_by_entity,
            crate::commands::notes::note_version_list,
            crate::commands::notes::note_version_create,
            crate::commands::notes::note_version_restore,
            crate::commands::notes::note_save_attachment,
            crate::commands::notes::notebook_list,
            crate::commands::notes::notebook_create,
            crate::commands::notes::notebook_update,
            crate::commands::notes::notebook_delete,
            crate::commands::notes::note_archive,
            crate::commands::notes::note_unarchive,
            crate::commands::notes::note_list_archived,
            crate::commands::notes::note_backlinks,
            crate::commands::notes::note_suggestions,
            crate::commands::notes::note_tags_all,
            crate::commands::notes::note_unlinked_mentions,
            crate::commands::notes::inbox_create,
            crate::commands::notes::inbox_list,
            crate::commands::notes::inbox_delete,
            crate::commands::notes::note_insight_review,
            crate::commands::notes::note_insight_cache_get,
            crate::commands::notes::note_insight_save_flashcards,
            crate::commands::notes::note_insight_submit_quiz,
            crate::commands::notes::note_insight_regenerate_tab,
            crate::commands::notes::note_insight_debate,
            crate::commands::notes::note_insight_list_versions,
            crate::commands::notes::note_insight_get_evolution,
            crate::commands::notes::note_insight_get_version,
            crate::commands::notes::note_insight_generate_scenario,
            crate::commands::notes::note_insight_changes_summary,
            crate::commands::notes::note_insight_knowledge_growth,
            crate::commands::notes::note_insight_list_personas,
            crate::commands::notes::note_insight_create_persona,
            crate::commands::notes::note_insight_update_persona,
            crate::commands::notes::note_insight_delete_persona,
            crate::commands::notes::note_insight_toggle_persona,
            crate::commands::notes::note_insight_set_pins,
            crate::commands::notes::note_insight_rate_persona,
            crate::commands::notes::note_insight_auto_generate_persona,
            crate::commands::notes::note_insight_persona_chat,
            crate::commands::notes::note_insight_preview_scope,
            crate::commands::notes::flashcard_list_decks,
            crate::commands::notes::flashcard_get_due,
            crate::commands::notes::flashcard_record_review,
            crate::commands::notes::flashcard_get,
            crate::commands::notes::flashcard_create,
            crate::commands::notes::flashcard_update,
            crate::commands::notes::flashcard_list_cards,
            crate::commands::notes::flashcard_delete,
            crate::commands::notes::flashcard_get_all_due,
            crate::commands::notes::flashcard_total_due,
            crate::commands::notes::flashcard_list_struggling,
            crate::commands::notes::flashcard_generate,
            crate::commands::notes::flashcard_save_generated,
            crate::commands::notes::flashcard_submit_answer,
            crate::commands::notes::flashcard_explain_answer,
            crate::commands::notes::flashcard_generate_distractors,
            crate::commands::notes::flashcard_save_mode_preference,
            crate::commands::notes::flashcard_get_mode_preference,
            crate::commands::notes::flashcard_get_prerequisites,
            crate::commands::notes::flashcard_save_session,
            crate::commands::notes::flashcard_recent_learning_sessions,
            crate::commands::notes::note_retention_health,
            crate::commands::notes::note_editing_finished,
            crate::commands::notes::note_insight_tab_chat,
            crate::commands::notes::note_insight_clear_tab_chats,
            crate::commands::notes::note_import_files,
            crate::commands::notes::note_export,
            // objectives
            crate::commands::objectives::objective_create,
            crate::commands::objectives::objective_get,
            crate::commands::objectives::objective_update,
            crate::commands::objectives::objective_delete,
            // integrations
            crate::commands::integrations::ai_tools_detect,
            crate::commands::integrations::ai_tools_install,
            // oauth
            crate::commands::oauth::mcp_oauth_start,
            crate::commands::oauth::mcp_oauth_disconnect,
            // pending_memory
            crate::commands::pending_memory::list_pending_memories,
            crate::commands::pending_memory::approve_pending_memory,
            crate::commands::pending_memory::dismiss_pending_memory,
            // permissions
            crate::commands::permissions::permissions_check_accessibility,
            crate::commands::permissions::permissions_open_accessibility,
            // practice
            crate::commands::practice::practice_segment_note,
            crate::commands::practice::practice_start_session,
            crate::commands::practice::practice_submit_unit,
            crate::commands::practice::practice_confirm_unit,
            crate::commands::practice::practice_get_session,
            crate::commands::practice::practice_complete_session,
            crate::commands::practice::practice_list_sessions,
            // productivity
            crate::commands::productivity::productivity_today,
            crate::commands::productivity::productivity_timeline,
            crate::commands::productivity::productivity_focus_start,
            crate::commands::productivity::productivity_focus_end,
            crate::commands::productivity::productivity_focus_status,
            crate::commands::productivity::productivity_sessions,
            crate::commands::productivity::productivity_intelligence_sessions,
            crate::commands::productivity::productivity_weekly,
            crate::commands::productivity::productivity_categories,
            crate::commands::productivity::productivity_tracked_apps,
            crate::commands::productivity::productivity_summary_range,
            crate::commands::productivity::productivity_activity_feed,
            crate::commands::productivity::productivity_goals,
            crate::commands::productivity::productivity_pomodoro_start,
            crate::commands::productivity::productivity_time_entries,
            crate::commands::productivity::productivity_goal_create,
            crate::commands::productivity::productivity_goal_delete,
            crate::commands::productivity::productivity_goal_toggle,
            crate::commands::productivity::productivity_time_entry_create,
            crate::commands::productivity::productivity_time_entry_delete,
            crate::commands::productivity::productivity_category_upsert,
            crate::commands::productivity::productivity_category_delete,
            crate::commands::productivity::productivity_recategorize_app,
            crate::commands::productivity::productivity_insights,
            crate::commands::productivity::productivity_insight_dismiss,
            crate::commands::productivity::productivity_auto_focus_start,
            crate::commands::productivity::productivity_auto_focus_end,
            crate::commands::productivity::productivity_auto_focus_confirm,
            crate::commands::productivity::distraction_respond,
            crate::commands::productivity::productivity_projects_list,
            crate::commands::productivity::productivity_project_upsert,
            crate::commands::productivity::productivity_project_delete,
            crate::commands::productivity::productivity_weekly_assessment,
            crate::commands::productivity::productivity_calendar_events,
            crate::commands::productivity::calendar_sync_events,
            crate::commands::productivity::focus_session_start,
            crate::commands::productivity::focus_session_stop,
            crate::commands::productivity::focus_session_status,
            crate::commands::productivity::focus_session_pause,
            crate::commands::productivity::focus_session_resume,
            crate::commands::productivity::focus_session_extend,
            crate::commands::productivity::focus_session_start_break,
            crate::commands::productivity::focus_session_extend_work,
            crate::commands::productivity::focus_session_skip_break,
            crate::commands::productivity::focus_session_take_break,
            crate::commands::productivity::productivity_patterns,
            crate::commands::productivity::productivity_hourly_breakdown,
            // project_conversations
            crate::commands::project_conversations::project_conversations_list,
            // project_memories
            crate::commands::project_memories::project_memories_list,
            crate::commands::project_memories::project_memories_by_type,
            // project_sources
            crate::commands::project_sources::project_source_create,
            crate::commands::project_sources::project_source_delete,
            crate::commands::project_sources::project_source_list,
            // projects
            crate::commands::projects::project_create,
            crate::commands::projects::project_get,
            crate::commands::projects::project_update,
            crate::commands::projects::project_delete,
            crate::commands::projects::project_archive,
            crate::commands::projects::project_update_instructions,
            crate::commands::projects::project_update_role,
            crate::commands::projects::project_health_metrics,
            // reforge
            crate::commands::reforge::reforge_state,
            crate::commands::reforge::reforge_skill_names,
            crate::commands::reforge::reforge_skill_versions,
            crate::commands::reforge::reforge_skill_version_detail,
            crate::commands::reforge::reforge_skill_reset,
            // retention_history
            crate::commands::retention_history::retention_history,
            // review_stats
            crate::commands::review_stats::review_stats_summary,
            // shortcuts
            crate::commands::shortcuts::shortcuts_get,
            crate::commands::shortcuts::shortcuts_update,
            // squads
            crate::commands::squads::list_squads,
            crate::commands::squads::get_squad,
            crate::commands::squads::create_squad,
            crate::commands::squads::update_squad,
            crate::commands::squads::delete_squad,
            crate::commands::squads::add_squad_member,
            crate::commands::squads::remove_squad_member,
            // status
            crate::commands::status::agent_status,
            // status_badge
            crate::commands::status_badge::show_status_badge,
            // tasks
            crate::commands::tasks::task_get,
            crate::commands::tasks::task_list,
            crate::commands::tasks::task_create,
            crate::commands::tasks::task_update,
            crate::commands::tasks::task_delete,
            crate::commands::tasks::task_toggle_complete,
            crate::commands::tasks::task_list_children,
            crate::commands::tasks::today_tasks,
            crate::commands::tasks::project_list,
            crate::commands::tasks::objective_list,
            crate::commands::tasks::task_add_dependency,
            crate::commands::tasks::task_list_dependencies,
            crate::commands::tasks::task_add_attachment,
            crate::commands::tasks::task_list_attachments,
            crate::commands::tasks::task_add_time_entry,
            crate::commands::tasks::task_list_time_entries,
            crate::commands::tasks::cross_domain_check,
            // timeline
            crate::commands::timeline::timeline_query,
            // view
            crate::commands::view::view_set_active,
            crate::commands::view::view_clear_active,
            crate::commands::view::view_get_active,
            // voice
            crate::commands::voice::voice_start_dictation,
            crate::commands::voice::voice_stop_dictation,
            crate::commands::voice::voice_simulate_event,
            crate::commands::voice::voice_list_devices,
            crate::commands::voice::voice_model_status,
            crate::commands::voice::voice_download_model,
            crate::commands::voice::voice_delete_model,
            crate::commands::voice::voice_test_persona,
            // voice_conversation
            crate::commands::voice_conversation::voice_conversation_start,
            crate::commands::voice_conversation::voice_conversation_pause,
            crate::commands::voice_conversation::voice_conversation_resume,
            crate::commands::voice_conversation::voice_conversation_interrupt,
            crate::commands::voice_conversation::voice_conversation_continue,
            crate::commands::voice_conversation::voice_conversation_new_session,
            crate::commands::voice_conversation::voice_conversation_end,
            crate::commands::voice_conversation::voice_conversation_status,
            // window
            crate::commands::window::resize_window,
            crate::commands::window::open_url,
            crate::commands::window::show_dashboard,
            crate::commands::window::quit_app,
            // work_context
            crate::commands::work_context::list_work_contexts,
            crate::commands::work_context::get_work_context,
            crate::commands::work_context::get_work_context_detail,
            crate::commands::work_context::update_work_context,
            crate::commands::work_context::archive_work_context,
            crate::commands::work_context::merge_work_contexts,
            crate::commands::work_context::search_work_contexts,
            crate::commands::work_context::get_context_timeline,
            crate::commands::work_context::get_context_resume_data,
            crate::commands::work_context::get_inference_stats,
            crate::commands::work_context::get_dashboard_intelligence,
            crate::commands::work_context::update_inference_config,
            // workflows
            crate::commands::workflows::workflow_list,
            crate::commands::workflows::workflow_get,
            crate::commands::workflows::workflow_get_effective,
            crate::commands::workflows::workflow_create,
            crate::commands::workflows::workflow_delete,
            crate::commands::workflows::label_create,
            crate::commands::workflows::label_update,
            crate::commands::workflows::label_delete,
            crate::commands::workflows::label_reorder,
            // workspace
            crate::commands::workspace::workspace_list_files,
            crate::commands::workspace::workspace_read_file,
            crate::commands::workspace::workspace_write_file,
        ])
        .events(collect_events![])
}
