[package]
name = "lsp-client"
version.workspace = true
edition.workspace = true

[dependencies]
async-lsp = "0.2"
lsp-types = "0.97"
tokio = { workspace = true, features = ["process", "io-util", "sync"] }
tracing = { workspace = true }
common = { path = "../common" }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
